import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import * as client from '../data/client'
import type { Digest, LoadState } from '../types'
import { formatDate, formatTime } from '../lib/format'
import { EmptyState } from '../components/shared/EmptyState'
import styles from './DigestsPage.module.css'

function DigestCard({ digest, onDeleted }: { digest: Digest; onDeleted: () => void }) {
  const handleDelete = async () => {
    if (!window.confirm('Delete this digest?')) return
    await client.deleteDigest(digest.id)
    onDeleted()
  }

  return (
    <div className={styles.card}>
      <div className={styles.cardHead}>
        <div>
          <div className={styles.period}>
            {formatDate(digest.periodStart)} – {formatDate(digest.periodEnd)}
          </div>
          <div className={styles.meta}>
            Generated by {digest.createdByName ?? 'Unknown'} · {formatDate(digest.createdAt)}, {formatTime(digest.createdAt)}
          </div>
        </div>
        <button className={styles.deleteButton} onClick={handleDelete} aria-label="Delete digest">
          ×
        </button>
      </div>

      <p className={styles.summary}>{digest.summary}</p>

      {digest.highlights.length > 0 && (
        <div className={styles.highlights}>
          {digest.highlights.map((h) => (
            <Link key={h.billId} to={`/bills/${h.billId}`} className={styles.highlightChip}>
              {h.identifier} — {h.detail}
            </Link>
          ))}
        </div>
      )}

      <div className={styles.sections}>
        {digest.sections.map((section) => (
          <div key={section.title} className={styles.section}>
            <div className={styles.sectionTitle}>{section.title}</div>
            <ul className={styles.sectionList}>
              {section.items.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  )
}

export function DigestsPage() {
  const [digests, setDigests] = useState<LoadState<Digest[]>>({ status: 'loading' })
  const [generating, setGenerating] = useState(false)

  const load = () => {
    client
      .getDigests()
      .then((data) => setDigests(data.length === 0 ? { status: 'empty' } : { status: 'ready', data }))
      .catch(() => setDigests({ status: 'empty' }))
  }

  useEffect(load, [])

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      await client.generateDigest()
      load()
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className={styles.page}>
      <div className={styles.header}>
        <div>
          <h1 className={styles.title}>Digests</h1>
          <p className={styles.subhead}>
            Dated recaps covering everything since the last one — copy one out for a board update or a coalition
            newsletter, or just keep it for the record.
          </p>
        </div>
        <button className={styles.generateButton} onClick={handleGenerate} disabled={generating}>
          {generating ? 'Generating…' : '+ Generate digest'}
        </button>
      </div>

      {digests.status === 'loading' && <div className="skeleton" style={{ height: 200, marginTop: 16 }} />}
      {digests.status === 'empty' && (
        <EmptyState message="No digests yet. Generate one to capture everything that's happened so far." />
      )}

      {digests.status === 'ready' && (
        <div className={styles.list}>
          {digests.data.map((d) => (
            <DigestCard key={d.id} digest={d} onDeleted={load} />
          ))}
        </div>
      )}
    </div>
  )
}
