-- Retrofits every workspace-layer table with real workspace scoping, and
-- retires team_members in favor of real accounts (users/workspace_members
-- from 014). This is pre-launch software with no real coalition data —
-- everything below is 100% synthetic, regenerated by seedWorkspace.ts on
-- every run — so this ships as a clean cut (truncate, then alter) rather
-- than a data-preserving migration, and team_members is dropped outright at
-- the end rather than kept around as backward-compat cruft.
--
-- tracked_bills and followed_committees had bill_id/committee_id alone as
-- their primary key, which only makes sense for a single global list — two
-- workspaces must be able to independently track/follow the same real bill
-- or committee, so those become composite keys.
--
-- FK columns that used to point at team_members(id) (assignee_id, actor_id,
-- author_id, created_by, followed_by) now point at users(id) instead of
-- workspace_members(id): every workspace-scoped table already carries its
-- own workspace_id directly, so attribution doesn't need to be derived by
-- joining through membership — and pointing at the real account means
-- history stays intact even if that person is later removed from the
-- workspace.

TRUNCATE tracked_bills, activity_log, notes, bill_tags, tags,
         subject_watches, followed_committees, testimony, digests, saved_views
  CASCADE;

ALTER TABLE tracked_bills
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT tracked_bills_assignee_id_fkey,
  DROP CONSTRAINT tracked_bills_pkey;
ALTER TABLE tracked_bills ALTER COLUMN assignee_id TYPE INTEGER USING NULL;
ALTER TABLE tracked_bills
  ADD PRIMARY KEY (workspace_id, bill_id),
  ADD CONSTRAINT tracked_bills_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES users(id);
CREATE INDEX idx_tracked_bills_workspace ON tracked_bills(workspace_id);

ALTER TABLE followed_committees
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT followed_committees_followed_by_fkey,
  DROP CONSTRAINT followed_committees_pkey;
ALTER TABLE followed_committees ALTER COLUMN followed_by TYPE INTEGER USING NULL;
ALTER TABLE followed_committees
  ADD PRIMARY KEY (workspace_id, committee_id),
  ADD CONSTRAINT followed_committees_followed_by_fkey FOREIGN KEY (followed_by) REFERENCES users(id);

ALTER TABLE tags
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT tags_name_key,
  DROP CONSTRAINT tags_created_by_fkey;
ALTER TABLE tags ALTER COLUMN created_by TYPE INTEGER USING NULL;
ALTER TABLE tags
  ADD CONSTRAINT tags_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id),
  ADD CONSTRAINT tags_workspace_name_key UNIQUE (workspace_id, name);
CREATE INDEX idx_tags_workspace ON tags(workspace_id);

ALTER TABLE activity_log
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT activity_log_actor_id_fkey;
ALTER TABLE activity_log ALTER COLUMN actor_id TYPE INTEGER USING NULL;
ALTER TABLE activity_log
  ADD CONSTRAINT activity_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES users(id);
CREATE INDEX idx_activity_log_workspace ON activity_log(workspace_id);

ALTER TABLE notes
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT notes_author_id_fkey;
ALTER TABLE notes ALTER COLUMN author_id TYPE INTEGER USING NULL;
ALTER TABLE notes
  ADD CONSTRAINT notes_author_id_fkey FOREIGN KEY (author_id) REFERENCES users(id);
CREATE INDEX idx_notes_workspace ON notes(workspace_id);

ALTER TABLE subject_watches
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT subject_watches_created_by_fkey;
ALTER TABLE subject_watches ALTER COLUMN created_by TYPE INTEGER USING NULL;
ALTER TABLE subject_watches
  ADD CONSTRAINT subject_watches_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
CREATE INDEX idx_subject_watches_workspace ON subject_watches(workspace_id);

ALTER TABLE testimony
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT testimony_author_id_fkey;
ALTER TABLE testimony ALTER COLUMN author_id TYPE INTEGER USING NULL;
ALTER TABLE testimony
  ADD CONSTRAINT testimony_author_id_fkey FOREIGN KEY (author_id) REFERENCES users(id);
CREATE INDEX idx_testimony_workspace ON testimony(workspace_id);

ALTER TABLE digests
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  DROP CONSTRAINT digests_created_by_fkey;
ALTER TABLE digests ALTER COLUMN created_by TYPE INTEGER USING NULL;
ALTER TABLE digests
  ADD CONSTRAINT digests_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
CREATE INDEX idx_digests_workspace ON digests(workspace_id);

-- saved_views keeps its app-composed TEXT id (already effectively unique)
-- but gains workspace scoping and, newly, an owner — needed so "delete your
-- own saved view" vs. "an admin can delete anyone's" is expressible at all.
ALTER TABLE saved_views
  ADD COLUMN workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
  ADD COLUMN created_by INTEGER REFERENCES users(id);
CREATE INDEX idx_saved_views_workspace ON saved_views(workspace_id);

-- bill_tags gets no workspace_id of its own: every row is created alongside
-- a tag that's already workspace-scoped, and every query already joins
-- tags, so a duplicate column would just be another thing to keep in sync.

DROP TABLE team_members;
